-- MySQL Script generated by MySQL Workbench
-- seg 23 ago 2021 15:44:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `promel`.`association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `cnpj` VARCHAR(45) NOT NULL,
    `invite_code` VARCHAR(45) NULL,
    `creation_date` DATETIME NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

CREATE UNIQUE INDEX `cnpj_UNIQUE` ON `association` (`cnpj` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `role` VARCHAR(45) NOT NULL,
    `details` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promel`.`user_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_auth` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `role_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_user_auth_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_user_auth_role1_idx` ON `user_auth` (`role_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_account` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `creation_date` DATETIME NOT NULL,
    `phone` VARCHAR(45) NULL,
    `association_id` INT NULL,
    `user_auth_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_user_account_association1`
    FOREIGN KEY (`association_id`)
    REFERENCES `association` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_account_user_auth1`
    FOREIGN KEY (`user_auth_id`)
    REFERENCES `user_auth` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_user_account_association1_idx` ON `user_account` (`association_id` ASC) VISIBLE;

CREATE INDEX `fk_user_account_user_auth1_idx` ON `user_account` (`user_auth_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`production_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production_unit` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `total_production` DECIMAL(12,4) NOT NULL,
    `last_modification_date` DATETIME NOT NULL,
    `user_account_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_production_unit_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_production_unit_user_account1_idx` ON `production_unit` (`user_account_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`hive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hive` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `identification_code` VARCHAR(45) NOT NULL,
    `description` VARCHAR(255) NULL,
    `creation_date` DATETIME NOT NULL,
    `production_unit_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_hive_production_unit1`
    FOREIGN KEY (`production_unit_id`)
    REFERENCES `production_unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_hive_production_unit1_idx` ON `hive` (`production_unit_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `variables` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `weight` DECIMAL(4,2) NULL,
    `umidity` DECIMAL(5,2) NULL,
    `temperature` DECIMAL(5,2) NULL,
    `read_date` DATETIME NULL,
    `hive_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_variables_hive1`
    FOREIGN KEY (`hive_id`)
    REFERENCES `hive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_variables_hive1_idx` ON `variables` (`hive_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`production_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production_status` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `details` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promel`.`honey_production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honey_production` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `harvest_date` DATETIME NOT NULL,
    `association_id` INT NOT NULL,
    `production_status_id` INT NOT NULL,
    `end_date` DATETIME NULL,
    `total_production` DECIMAL(12,4) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_harvest_association1`
    FOREIGN KEY (`association_id`)
    REFERENCES `association` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_harvest_production_status1`
    FOREIGN KEY (`production_status_id`)
    REFERENCES `production_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_harvest_association1_idx` ON `honey_production` (`association_id` ASC) VISIBLE;

CREATE INDEX `fk_harvest_production_status1_idx` ON `honey_production` (`production_status_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `description` VARCHAR(255) NULL,
    `name` VARCHAR(255) NOT NULL,
    `creation_date` DATETIME NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promel`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `association_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_stock_association1`
    FOREIGN KEY (`association_id`)
    REFERENCES `association` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_stock_association1_idx` ON `stock` (`association_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`unity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unity_type` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promel`.`product_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_stock` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `quantity` INT NOT NULL,
    `price_per_unity` DECIMAL(9,4) NOT NULL,
    `unity_type_id` INT NOT NULL,
    `product_id` INT NOT NULL,
    `stock_id` INT NOT NULL,
    `last_modification_date` DATETIME NOT NULL,
    `previous_price` DECIMAL(9,4) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_product_stock_unity_type1`
    FOREIGN KEY (`unity_type_id`)
    REFERENCES `unity_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_product_stock_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_product_stock_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_product_stock_unity_type1_idx` ON `product_stock` (`unity_type_id` ASC) VISIBLE;

CREATE INDEX `fk_product_stock_product1_idx` ON `product_stock` (`product_id` ASC) VISIBLE;

CREATE INDEX `fk_product_stock_stock1_idx` ON `product_stock` (`stock_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sale` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `creation_date` DATETIME NOT NULL,
    `description` VARCHAR(255) NULL,
    `price_per_unity_at_date` DECIMAL(9,4) NOT NULL,
    `item_quantity` INT NOT NULL,
    `product_stock_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_sale_product_stock1`
    FOREIGN KEY (`product_stock_id`)
    REFERENCES `product_stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_sale_product_stock1_idx` ON `sale` (`product_stock_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`user_product_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_product_request` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `request_date` DATETIME NOT NULL,
    `details` VARCHAR(255) NULL,
    `user_account_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_user_product_request_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_user_product_request_user_account1_idx` ON `user_product_request` (`user_account_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`alert_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alert_event` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(45) NOT NULL,
    `creation_date` DATETIME NOT NULL,
    `details` VARCHAR(255) NULL,
    `user_account_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_alert_event_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_alert_event_user_account1_idx` ON `alert_event` (`user_account_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`money_amount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money_amount` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `amount` DECIMAL(12,4) NOT NULL,
    `association_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_money_amount_association1`
    FOREIGN KEY (`association_id`)
    REFERENCES `association` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_money_amount_association1_idx` ON `money_amount` (`association_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `cost` DECIMAL(10,4) NOT NULL,
    `description` VARCHAR(255) NULL,
    `creation_date` DATETIME NOT NULL,
    `association_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_expense_association1`
    FOREIGN KEY (`association_id`)
    REFERENCES `association` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_expense_association1_idx` ON `expense` (`association_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`money_operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money_operation` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `operation_date` DATETIME NOT NULL,
    `details` VARCHAR(255) NULL,
    `money_value` DECIMAL(12,4) NOT NULL,
    `previous_money_amount` DECIMAL(12,4) NOT NULL,
    `association_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_money_operation_association1`
    FOREIGN KEY (`association_id`)
    REFERENCES `association` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_money_operation_association1_idx` ON `money_operation` (`association_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`product_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_request` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `item_quantity` INT NOT NULL,
    `user_product_request_id` INT NOT NULL,
    `product_stock_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_product_request_user_product_request1`
    FOREIGN KEY (`user_product_request_id`)
    REFERENCES `user_product_request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_product_request_product_stock1`
    FOREIGN KEY (`product_stock_id`)
    REFERENCES `product_stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_product_request_user_product_request1_idx` ON `product_request` (`user_product_request_id` ASC) VISIBLE;

CREATE INDEX `fk_product_request_product_stock1_idx` ON `product_request` (`product_stock_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `promel`.`production_unit_has_honey_production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production_unit_has_honey_production` (
    `production_unit_id` INT NOT NULL AUTO_INCREMENT,
    `honey_production_id` INT NOT NULL,
    `number_extracted_frames` INT NOT NULL,
    `parcial_production` DECIMAL(6,4) NOT NULL,
    `hive_id` INT NOT NULL,
    PRIMARY KEY (`production_unit_id`, `honey_production_id`),
    CONSTRAINT `fk_production_unit_has_honey_production_production_unit1`
    FOREIGN KEY (`production_unit_id`)
    REFERENCES `production_unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_production_unit_has_honey_production_honey_production1`
    FOREIGN KEY (`honey_production_id`)
    REFERENCES `honey_production` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_production_unit_has_honey_production_hive1`
    FOREIGN KEY (`hive_id`)
    REFERENCES `hive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_production_unit_has_honey_production_honey_production1_idx` ON `production_unit_has_honey_production` (`honey_production_id` ASC) VISIBLE;

CREATE INDEX `fk_production_unit_has_honey_production_production_unit1_idx` ON `production_unit_has_honey_production` (`production_unit_id` ASC) VISIBLE;

CREATE INDEX `fk_production_unit_has_honey_production_hive1_idx` ON `production_unit_has_honey_production` (`hive_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;